"""Configurable thresholds and weights for the RAD scoring engine."""

# Layer 0 — Experience-Level Anomaly Detection
ANOMALY_THRESHOLD_MULTIPLIER = 3.0
BASELINE_REFUND_RATE_PER_EXPERIENCE = 0.05
ANOMALY_MIN_COUNT = 3

# Layer 2 — Signal Weights (sum to 100)
WEIGHT_REFUND_FREQUENCY = 30
WEIGHT_NO_SHOW_HISTORY = 25
WEIGHT_EMAIL_ENGAGEMENT = 15
WEIGHT_REFUND_TIMING = 15
WEIGHT_EXPERIENCE_VALUE = 8
WEIGHT_TENURE = 7

# Layer 2 — Thresholds
REFUND_RATE_HIGH_RISK = 0.40
REFUND_RATE_LOW_RISK = 0.10
RECENCY_FULL_WEIGHT_DAYS = 90
RECENCY_DECAY_DAYS = 180
RECENCY_MIN_WEIGHT = 0.1

# Layer 3 — Request Modifiers
NON_CANCELABLE_AMPLIFIER = 1.3
HIGH_VALUE_THRESHOLD_PERCENTILE = 85
POST_EXPERIENCE_MODIFIER = 1.2

# Classification Thresholds
LOW_RISK_CEILING = 30
HIGH_RISK_FLOOR = 60
